/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coding.challenge2;

import org.testng.Assert;
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {

    @Test(groups = {"smoke"})
    public void canary() {
        Assert.assertEquals(true,true);
    }
}
